require_relative "./super_smash/version"
require_relative "./super_smash/cli"
require_relative "./super_smash/api"
require_relative "./super_smash/character"
require 'rest-client'
require 'json'
require 'httparty'
require 'pry'
require 'colorize'
